version: 0.1

phases:
  install:
    commands:
     
  build:
    commands:
      - aws s3 rm --recursive "s3://${ARTIFACTS_BUCKET}/"

  post_build:
    commands:
    
artifacts:
  files:
    - index.html
    - appspec.yml
    